api_platform:
    title: 'Aln-Symfony'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/ApiPlatform/Dto']
    formats:
        json: [ 'application/json' ]
        html:     ['text/html']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
        versions: [3]

when@prod:
    api_platform:
        enable_docs: false
        enable_entrypoint: false