api_platform:
  title: Aln-Symfony
  description: 'More infos on Github: https://github.com/Dean151/Aln-Symfony'
  version: 0.3.0
  show_webby: false
  formats:
    json: [ 'application/json' ]
    jsonld: ['application/ld+json']
  docs_formats:
    json: [ 'application/json' ]
    jsonld: ['application/ld+json']
    jsonopenapi: [ 'application/vnd.openapi+json' ]
    html: [ 'text/html' ]
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    extra_properties:
      #standard_put: true
      rfc_7807_compliant_errors: true
    normalization_context:
      skip_null_values: false
  event_listeners_backward_compatibility_layer: false
  keep_legacy_inflector: false
  swagger:
    api_keys:
      JWT:
        name: 'Authorization'
        type: 'header'
