version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:latest'
    volumes:
       - aln-db-data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - 3306:3306
###< doctrine/doctrine-bundle ###
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672

volumes:
###> doctrine/doctrine-bundle ###
  aln-db-data:
###< doctrine/doctrine-bundle ###
