version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-10.11}
    environment:
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
    volumes:
      - aln_database_data:/var/lib/mysql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  rabbitmq:
    image: rabbitmq:3.7-management

volumes:
###> doctrine/doctrine-bundle ###
  aln_database_data:
###< doctrine/doctrine-bundle ###
